name: 'Terragrunt GitHub Actions'
on:
  - pull_request

env:
  tofu_version: '1.8.1'
  tg_version: '0.67.0'
  working_dir: 'terragrunt'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  plan:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Generate Plan
        id: terragrunt-plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan -out=plan.out'

      - name: List Files in Directory
        run: ls -al

      - name: Debug Plan Output
        run: |
          if [ -f "plan.out" ]; then
            echo "plan.out exists.";
          else
            echo "plan.out does not exist.";
            exit 1;
          fi

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: terragrunt-plan
          path: plan.out

      - name: Post Plan to PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('plan.out', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Terragrunt Plan\n\n\`\`\`\n${plan}\n\`\`\``
            });

  deploy:
    runs-on: ubuntu-latest
    needs: [ plan ]
    environment: 'dev'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: terragrunt-plan

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'apply plan.out'