name: 'Terragrunt GitHub Actions'
on:
  - pull_request

env:
  tofu_version: '1.8.1'
  tg_version: '0.67.0'
  working_dir: 'terragrunt'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  plan:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Generate Plan
        id: terragrunt-plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan -out=${{ github.workspace }}/plan.out'
          tg_comment: 'true'

      - name: List Files in Directory
        run: ls ${{ github.workspace }} -al

      - name: Output Plan Logs terragrunt
        run: cat ${{ github.workspace }}/plan.out || echo "Plan logs not found in terragrunt dir."

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: terragrunt-plan
          path: ${{ github.workspace }}/plan.out


  deploy:
    runs-on: ubuntu-latest
    needs: [ plan ]
    environment: 'dev'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: terragrunt-plan

      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'apply plan.out'